#pragma config(Sensor, S1,     seer,            sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void follow()
{



task main()



}
void thru()
{


