#pragma config(Motor,  motorC,          Grabber,       tmotorEV3_Medium, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard *//

task main()
{
	while(getMotorEncoder(Grabber) < 2980)
	{
		motor[Grabber] = -100;


}

}
