#pragma config(Sensor, S1,     seer,            sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

	task main()
	{
		while(true)
		{
	motor[left]= 100;
	motor[right]= -80;
	wait1Msec(240);
	motor[left]= -100;
	motor[right]= 80;
	wait1Msec(240);
}
}
